name: "✨ Feature Request"
description: Suggest a new feature for the Nexora web app
title: "[Feature]: "
labels: ["feature", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe the problem and your proposed solution.

  - type: textarea
    id: problem
    attributes:
      label: Problem
      description: What user problem are we solving?
      placeholder: "Users currently cannot..."
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: What would you like to see implemented?
      placeholder: "Add a dark mode toggle..."
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives
      description: Have you considered other approaches?

  - type: textarea
    id: impact
    attributes:
      label: Impact
      description: Who benefits and how?
