name: PR Title Check

on:
  pull_request:
    types: [opened, edited, synchronize, reopened, ready_for_review]

permissions:
  pull-requests: read
  statuses: write

jobs:
  check-title:
    runs-on: ubuntu-latest
    steps:
      - name: Validate PR title against Conventional Commits
        uses: amannn/action-semantic-pull-request@v5
        with:
          types: |
            feat
            fix
            chore
            docs
            style
            refactor
            perf
            test
            ci
            build
            revert
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
